# Generated by Django 4.1.7 on 2023-03-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='detachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sysVRO.detachment', verbose_name='Отряд'),
        ),
    ]
