# Generated by Django 4.1.7 on 2023-03-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0005_detachment_alter_profile_detachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профили', 'verbose_name_plural': 'профиль'},
        ),
    ]
