# Generated by Django 4.1.7 on 2023-03-18 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0006_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detachment',
            options={'verbose_name': 'Отряд', 'verbose_name_plural': 'отряды'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-beginning_date'], 'verbose_name': 'Мероприятие', 'verbose_name_plural': 'мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name'], 'verbose_name': 'Учебное заведение', 'verbose_name_plural': 'учебные заведения'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'ordering': ['name'], 'verbose_name': 'Тип мероприятия', 'verbose_name_plural': 'типы мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'профили'},
        ),
    ]
