# Generated by Django 4.1.7 on 2023-03-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0007_alter_detachment_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, verbose_name='Ссылка ВК'),
        ),
    ]
