# Generated by Django 4.1.7 on 2023-03-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0008_alter_profile_link_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='link_vk',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ссылка ВК'),
        ),
    ]
