# Generated by Django 4.1.7 on 2023-03-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0009_alter_profile_link_vk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kind',
            new_name='EventKind',
        ),
        migrations.AddField(
            model_name='event',
            name='form',
            field=models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн')], default='offline', max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='kind',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Тип мероприятия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='link_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, verbose_name='Ссылка ВК'),
        ),
    ]
