# Generated by Django 4.1.7 on 2023-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0010_rename_kind_eventkind_event_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='kind',
        ),
        migrations.AddField(
            model_name='event',
            name='kind',
            field=models.ManyToManyField(blank=True, to='sysVRO.eventkind', verbose_name='Тип мероприятия'),
        ),
    ]
