# Generated by Django 4.1.7 on 2023-03-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0011_remove_event_kind_event_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name='Название')),
                ('rgb', models.CharField(max_length=7, verbose_name='#rrggbb')),
            ],
            options={
                'verbose_name': 'Цвет мероприятия',
                'verbose_name_plural': 'цвета мероприятий',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='scale',
            field=models.CharField(choices=[('detachment', 'Отрядное'), ('institution', 'Учебного заведения'), ('region', 'Региональное'), ('country', 'Всероссийское')], default='detachment', max_length=20, verbose_name='Масштаб'),
        ),
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.CharField(choices=[('offline', 'Офлайн'), ('online', 'Онлайн')], default='offline', max_length=7, verbose_name='Форма проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='event/img', verbose_name='Картинка мероприятия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='media/users/%Y/%m/%d', verbose_name='Аватарка'),
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sysVRO.eventcolor', verbose_name='Цвет мероприятия'),
        ),
    ]
