# Generated by Django 4.1.7 on 2023-03-19 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0012_eventcolor_event_scale_alter_event_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin',
            field=models.ManyToManyField(blank=True, to='sysVRO.profile', verbose_name='Ответственные в системе'),
        ),
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылки на отчетные посты'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Организатор'),
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, default='+7', max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sysVRO.eventcolor', verbose_name='Цвет для градиента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
    ]
