# Generated by Django 4.1.7 on 2023-03-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0013_event_admin_event_links_event_organizer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'направления',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='detachment',
            name='about',
            field=models.CharField(blank=True, default='', max_length=400, verbose_name='Об отряде'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='emblem',
            field=models.ImageField(blank=True, upload_to='media/emblems/%Y/%m/%d', verbose_name='Эмблема'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='flag',
            field=models.ImageField(blank=True, upload_to='media/flags/%Y/%m/%d', verbose_name='Флаг'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sysVRO.institution', verbose_name='Учебное заведение'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='link_vk',
            field=models.CharField(blank=True, default='https://vk.com/', max_length=50, verbose_name='Ссылка ВК'),
        ),
        migrations.AddField(
            model_name='institution',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='profile',
            name='membership_fee',
            field=models.BooleanField(default=False, verbose_name='Членский взнос оплачен'),
        ),
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sysVRO.area', verbose_name='Направление'),
        ),
    ]
