# Generated by Django 4.1.7 on 2023-03-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0014_area_detachment_about_detachment_emblem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Количество баллов')),
                ('about', models.CharField(blank=True, default='', max_length=200, verbose_name='Описание выполненной работы')),
                ('organizer', models.BooleanField(default=False, verbose_name='Организатор')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sysVRO.event', verbose_name='Мероприятие')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sysVRO.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'оценки',
                'ordering': ['event'],
            },
        ),
    ]
