# Generated by Django 4.1.7 on 2023-03-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0015_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Полное название'),
        ),
    ]
