# Generated by Django 4.1.7 on 2023-03-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0016_alter_institution_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachment',
            name='emblem',
            field=models.ImageField(blank=True, upload_to='emblems/%Y/%m/%d', verbose_name='Эмблема'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='flag',
            field=models.ImageField(blank=True, upload_to='flags/%Y/%m/%d', verbose_name='Флаг'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d', verbose_name='Аватарка'),
        ),
    ]
