# Generated by Django 4.1.7 on 2023-03-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0017_alter_detachment_emblem_alter_detachment_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='position',
        ),
    ]
