# Generated by Django 4.1.7 on 2023-03-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0019_rename_detachment_profile_detachment_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='detachment_member',
            new_name='detachment',
        ),
        migrations.AddField(
            model_name='detachment',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commander', to='sysVRO.profile', verbose_name='Командир'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='commissar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissar', to='sysVRO.profile', verbose_name='Комиссар'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretary', to='sysVRO.profile', verbose_name='Мастер-методист'),
        ),
        migrations.AddField(
            model_name='detachment',
            name='specialist',
            field=models.ManyToManyField(blank=True, null=True, related_name='specialist', to='sysVRO.profile', verbose_name='Специалист'),
        ),
    ]
