# Generated by Django 4.1.7 on 2023-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0020_rename_detachment_member_profile_detachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachment',
            name='specialist',
            field=models.ManyToManyField(blank=True, related_name='specialist', to='sysVRO.profile', verbose_name='Специалист'),
        ),
    ]
