# Generated by Django 4.1.7 on 2023-03-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0021_alter_detachment_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachment',
            name='commander',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commander', to='sysVRO.profile', verbose_name='Командир'),
        ),
    ]
