# Generated by Django 4.1.7 on 2023-03-24 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0022_alter_detachment_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detachment',
            name='commissar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commissar', to='sysVRO.profile', verbose_name='Комиссар'),
        ),
        migrations.AlterField(
            model_name='detachment',
            name='secretary',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secretary', to='sysVRO.profile', verbose_name='Мастер-методист'),
        ),
    ]
