# Generated by Django 4.1.7 on 2023-03-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0023_alter_detachment_commissar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Должность'),
        ),
    ]
