# Generated by Django 4.1.7 on 2023-03-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0024_profile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detachment',
            name='commissar',
        ),
        migrations.RemoveField(
            model_name='detachment',
            name='secretary',
        ),
        migrations.RemoveField(
            model_name='detachment',
            name='specialist',
        ),
    ]
