# Generated by Django 4.1.7 on 2023-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0025_remove_detachment_commissar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, choices=[('', 'Без должности'), ('Комиссар', 'Комиссар'), ('Мастер-методист', 'Мастер-методист'), ('Специалист', 'Специалист'), ('Командир', 'Командир')], default='', max_length=20, verbose_name='Должность'),
        ),
    ]
