# Generated by Django 4.1.7 on 2023-03-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0026_alter_profile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.CharField(choices=[('Офлайн', 'Офлайн'), ('Онлайн', 'Онлайн')], default='offline', max_length=7, verbose_name='Форма проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scale',
            field=models.CharField(choices=[('Отрядное', 'Отрядное'), ('Учебного заведения', 'Учебного заведения'), ('Региональное', 'Региональное'), ('Всероссийское', 'Всероссийское')], default='Отрядное', max_length=20, verbose_name='Масштаб'),
        ),
    ]
