# Generated by Django 4.1.7 on 2023-03-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0027_alter_event_form_alter_event_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, default='Волгоград', max_length=50, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='form',
            field=models.CharField(choices=[('Офлайн', 'Офлайн'), ('Онлайн', 'Онлайн')], default='Офлайн', max_length=7, verbose_name='Форма проведения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
