# Generated by Django 4.1.7 on 2023-03-30 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0029_alter_event_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='sysVRO.profile', verbose_name='Контакт организатора'),
        ),
    ]
