# Generated by Django 4.1.7 on 2023-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0030_event_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
