# Generated by Django 5.0.6 on 2024-06-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysVRO', '0031_mark_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='abbreviation',
            field=models.CharField(db_index=True, max_length=50, null=True, verbose_name='Аббревиатура'),
        ),
    ]
